name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Format & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath
          tools: composer
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Pint (Format Check)
        run: composer format -- --test

      - name: Run Pest Tests
        run: composer test
